apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogdb-deployment
  labels:
    app: blogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogdb
  template:
    metadata:
      labels:
        app: blogdb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: blogdb-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: blogdb-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: blogdb-service
spec:
  selector:
    app: blogdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blogdb-config
data:
  mongo-url: blogdb-service
---
apiVersion: v1
kind: Secret
metadata:
  name: blogdb-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==