apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution-deployment
  labels:
    app: solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solution
  template:
    metadata:
      labels:
        app: solution
    spec:
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: solution-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solution-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: solution-service
spec:
  selector:
    app: solution
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solution-config
data:
  mongo-url: solution-service
---
apiVersion: v1
kind: Secret
metadata:
  name: solution-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==