server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: BlogDB
      host: ${DB_URL:localhost}
      username: ${USER_NAME}
      password: ${USER_PWD}
      authentication-database: admin
      port: 27017
  application:
    name: Blog-Service
opentracing:
  jaeger:
    enable-b3-propagation: true
  spring:
    web:
      client:
        enabled: true
      enabled: true


