server:
  port: 8084
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: haben.noreply@gmail.com
    password: ujoqyidzbeihnavu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
