server:
  port: 8084
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Mail-Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: haben.noreply@gmail.com
    password: ujoqyidzbeihnavu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
opentracing:
  jaeger:
    enable-b3-propagation: true
  spring:
    web:
      client:
        enabled: true
      enabled: true
