server:
  port: 9191
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true

      routes:
        - id: acc-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/account/**
          filters:
            - AuthenticationFilter

        - id: question-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/question/**
          filters:
            - AuthenticationFilter

        - id: chatroom-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/chatroom/**
          filters:
            - AuthenticationFilter


        - id: blog-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/blogs/**
          filters:
            - AuthenticationFilter
jwt:
  secret: AntonyoFinalBereket
  validity: 20
  authDisabled: true

