server:
  port: 9191
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: acc-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/account/**
          filters:
            - AuthenticationFilter

        - id: ord-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/question/**
          filters:
            - AuthenticationFilter

        - id: pro-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/chatroom/**
          filters:
            - AuthenticationFilter
jwt:
  secret: AntonyoFinalBereket
  validity: 20
  authDisabled: true

